version: "3"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  professor:
    build:
      dockerfile: Dockerfile
      context: ./professor
    container_name: professor
    ports:
      - "7002:7002"
    restart: always
    depends_on:
      - redis
    
  question_bank:
    build:
      dockerfile: Dockerfile
      context: ./question_bank
    container_name: question_bank
    ports:
      - "7005:7005"
    restart: always
    depends_on:
      - redis

  student:
    build:
      dockerfile: Dockerfile
      context: ./student
    container_name: student
    ports:
      - "7001:7001"
    restart: always
    depends_on:
      - redis

  subject:
    build:
      dockerfile: Dockerfile
      context: ./subject
    container_name: subject
    ports:
      - "7004:7004"
    restart: always
    depends_on:
      - redis

  tests:
    build:
      dockerfile: Dockerfile
      context: ./tests
    container_name: tests
    ports:
      - "7003:7003"
    restart: always
    depends_on:
      - redis

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    depends_on:
      - professor
      - question_bank
      - student
      - subject
      - tests
    ports:
      - 80:80

volumes:
  mongodata: